FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=America/New_York

RUN apt-get update
RUN apt-get install -y tzdata
RUN apt-get install -y nginx
ADD index.html /usr/share/nginx/html/index.html

ENTRYPOINT ["usr/sbin/nginx", "-g", "daemon off;"]
EXPOSE 80